accounts/urls.py
from django.urls import path

from accounts.views import *


app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('logout/', logout_view, name="logout"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"), #Oz prilozeniyamyzyn urls.py-na baglayarys
    path('post/', include("post.urls")),
    path('accounts/', include("accounts.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from post.views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name="index"),
    path('create/', post_create, name='create'),
    path('detail/<slug:slug>', post_detail, name="detail"), #postlary id-sy boyunca yuzlenip bolyar.meselem post/detail/2/
    path('update/<slug:slug>', post_update, name='update'),
    path('delete/<slug:slug>', post_delete, name='delete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def home_view(request):  # request isleg  diymegi anladyar. funksiya doredemizde hokman parametr gorkezmeli meselem request
    if request.user.is_authenticated:
        context = {
            'isim': "Guwanch",
            "detail": 'mashennik'
        }
    else:
        context = {
            'isim': "misafir",

        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Django dersleri {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    {% include 'header.html' %}

    {% include 'messages.html' %}



    {% block body %}

    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"> </script>
</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home'%}" class="navbar-brand">Django Dersleri</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Ara">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Yazi ekle</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Anasayfa</a></li>
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                <li><a href="#">Hakkımda</a></li>
                <li><a href="#">İletişim</a></li>
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">Üye ol</a></li>
                    <li><a href="{% url 'accounts:login' %}">Giriş</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:logout' %}">Çikiş</a></li>
                {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block title %} Anasayfa - {{ block.super }}{% endblock %}

{%  block body %}
    <div class="container-fluid">
        <div class="row" style="margin-bottom: 30px">
            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px">1 urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: #184fdc; height: 100px">2 urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: #4db76a; height: 100px">3 urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: #eaad10; height: 100px">4 urun</div>

        </div>
      <div class="row" style="margin-bottom: 30px">
            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px">1 urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: #184fdc; height: 100px">2 urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: #4db76a; height: 100px">3 urun</div>
            <div class="col-md-3 col-sm-6" style="background-color: #eaad10; height: 100px">4 urun</div>

        </div>

    Welcome {{ request.user.get_full_name }}
    </div>

{% endblock %}

templates/messages.html
 {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    {{ message }}
                </div>
            {% endfor %}
    {% endif %}